export default Data = [
  {label: '1 একর', value: '1'},
  {label: '2  অযুতাংশ', value: '2'},
  {label: '3 এয়র', value: '3'},
  {label: '4 কড়া', value: '4'},
  {label: '5 কন্ঠ', value: '5'},
  {label: '6 কাক', value: '6'},
  {label: '7 কাঠা', value: '7'},
  {label: '8 কানি', value: '8'},
  {label: '9 ক্রান্তি', value: '9'},
  {label: '10 গন্ডা', value: '10'},
  {label: '11 ছটাক', value: '11'},
  {label: '12 ডেসিমাল', value: '12'},
  {label: '13 তিল', value: '13'},
  {label: '14 দুল', value: '14'},
  {label: '15 ধনু', value: '15'},
  {label: '16 বর্গইঞ্চি', value: '16'},
  {label: '17 বর্গচেইন', value: '17'},
  {label: '18 বর্গফুট', value: '18'},
  {label: '19 বর্গমিটার', value: '19'},
  {label: '20 বর্গলিংক', value: '20'},
  {label: '21 বর্গহাত', value: '21'},
  {label: '22 বিঘা', value: '22'},
  {label: '23 রেনু', value: '23'},
  {label: '24 শতাংশ', value: '24'},
  {label: '25 হেক্টর', value: '25'},
  {label: '26 শতক', value: '26'},
  {label: '27 কাচ্চা কানি', value: '27'},
  {label: '28 সাই কানি ১', value: '28'},
  {label: '29 সাই কানি ২', value: '29'},
  {label: '30 ডিসিম', value: '30'},
  {label: '31 বর্গসেন্টিমিটার', value: '31'},
  {label: '32 বর্গকিলোমিটার', value: '32'},
  {label: '33 বর্গমাইল', value: '33'},
  {label: '34 বর্গগজ', value: '34'},
];
